In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,56,78,59]], np.int64)

In [4]:
myarr

array([[ 3,  4, 56, 78, 59]], dtype=int64)

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.size

5

In [7]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int64)

In [8]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
zeros = np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zeros.dtype

dtype('float64')

In [14]:
zeros.shape

(2, 5)

# range

In [15]:
rnge = np.arange(15)

In [16]:
rnge

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
rnge.dtype

dtype('int32')

In [18]:
rnge.size

15