# More Questions on NumPy

**Convert the matrix into a list**

In [1]:
import numpy as np

In [3]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a.tolist()

[[0, 1, 2], [3, 4, 5]]

**Get row numbers of NumPy array having element larger than X**

In [9]:
b = np.arange(3,39,3).reshape(3,4)
b

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [11]:
x = 16;

In [12]:
np.where(np.any(b > x,axis = 1))

(array([1, 2], dtype=int64),)

**Find indices of elements equal to zero in a NumPy array**

In [25]:
c = np.matrix([[1,2,0],[0,5,0],[6,0,0]])
c

matrix([[1, 2, 0],
        [0, 5, 0],
        [6, 0, 0]])

In [26]:
d = np.argwhere(c == 0)
d

array([[0, 2],
       [1, 0],
       [1, 2],
       [2, 1],
       [2, 2]], dtype=int64)

**How to get the indices of the sorted array using NumPy in Python?**

In [27]:
a1 = np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
np.argsort(a1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

**Calculate average values of two given NumPy arrays**

In [30]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
b = np.arange(3,38,4).reshape(3,3)
b

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [36]:
c1 = (a + b)/2
c1

array([[ 1.5,  4. ,  6.5],
       [ 9. , 11.5, 14. ],
       [16.5, 19. , 21.5]])

**Find the round off the values of the given matrix**

In [39]:
a1 = np.matrix([[1.3,2.5,6.7],[3.3,5.8,9.2]])
a1

matrix([[1.3, 2.5, 6.7],
        [3.3, 5.8, 9.2]])

In [40]:
a1.round()

matrix([[1., 2., 7.],
        [3., 6., 9.]])

**Determine the positive square-root of an array**

In [42]:
a2 = np.sqrt([[1,3,5,7]])
a2

array([[1.        , 1.73205081, 2.23606798, 2.64575131]])