In [1]:
import numpy as np

In [2]:
import time

In [3]:
import sys

# size in python

In [4]:
lst = range(1000)

In [5]:
print(sys.getsizeof(5)*len(lst))

28000


# size in numpy

In [6]:
array = np.arange(1000)

In [7]:
print(array.size*array.itemsize)

4000


# array

In [8]:
myarr = np.array([[1,2,3,4]], np.int64)

In [9]:
myarr

array([[1, 2, 3, 4]], dtype=int64)

In [10]:
a = np.array([[1,2],[3,4],[5,6]])

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a.ndim

2

In [14]:
a.size

6

In [15]:
a.shape

(3, 2)

In [16]:
a.itemsize

4

# complex

In [18]:
lst = np.array([[1,2],[5,7],[9,0]], dtype = complex)

In [19]:
lst

array([[1.+0.j, 2.+0.j],
       [5.+0.j, 7.+0.j],
       [9.+0.j, 0.+0.j]])

In [20]:
lst.size

6

In [21]:
lst.ndim

2

In [22]:
lst.itemsize

16

# zeros

In [24]:
arr = np.zeros((3,4))

In [25]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arry = np.ones((3,3))

In [29]:
arry

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
arry.dtype

dtype('float64')

In [31]:
arry.size

9

# arange

In [34]:
ar = np.arange((15))

In [35]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
b = np.arange(1,15,2)

In [40]:
b

array([ 1,  3,  5,  7,  9, 11, 13])

# linspace

In [46]:
c = np.linspace(1,20,23)

In [47]:
c

array([ 1.        ,  1.86363636,  2.72727273,  3.59090909,  4.45454545,
        5.31818182,  6.18181818,  7.04545455,  7.90909091,  8.77272727,
        9.63636364, 10.5       , 11.36363636, 12.22727273, 13.09090909,
       13.95454545, 14.81818182, 15.68181818, 16.54545455, 17.40909091,
       18.27272727, 19.13636364, 20.        ])

In [48]:
d = np.linspace(5,32,21)

In [49]:
d

array([ 5.  ,  6.35,  7.7 ,  9.05, 10.4 , 11.75, 13.1 , 14.45, 15.8 ,
       17.15, 18.5 , 19.85, 21.2 , 22.55, 23.9 , 25.25, 26.6 , 27.95,
       29.3 , 30.65, 32.  ])

# reshape

In [50]:
aa = np.array([[1,2],[3,5],[9,8]])

In [51]:
aa

array([[1, 2],
       [3, 5],
       [9, 8]])

In [52]:
aa.size

6

In [53]:
aa.shape

(3, 2)

In [54]:
aa.reshape(2,3)

array([[1, 2, 3],
       [5, 9, 8]])

In [55]:
aa

array([[1, 2],
       [3, 5],
       [9, 8]])

In [56]:
aa.ravel()

array([1, 2, 3, 5, 9, 8])

In [57]:
aa.min()

1

In [58]:
aa.max()

9

In [59]:
aa.argmin()

0

In [60]:
aa.argmax()

4

In [61]:
aa

array([[1, 2],
       [3, 5],
       [9, 8]])

In [62]:
np.sqrt(aa)

array([[1.        , 1.41421356],
       [1.73205081, 2.23606798],
       [3.        , 2.82842712]])

In [63]:
np.std(aa)

2.981423969999719

# axis

In [64]:
bb = np.array([[1,2],[3,4],[5,6]])

In [65]:
cc = np.array([[2,6],[4,8],[2,5]])

In [66]:
bb

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
cc

array([[2, 6],
       [4, 8],
       [2, 5]])

In [68]:
bb.sum(axis = 1)

array([ 3,  7, 11])

In [69]:
cc.sum(axis = 0)

array([ 8, 19])

In [70]:
 aa + bb

array([[ 2,  4],
       [ 6,  9],
       [14, 14]])

In [71]:
aa * bb

array([[ 1,  4],
       [ 9, 20],
       [45, 48]])

# slicing

In [74]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [75]:
a1[0:2]

array([1, 2])

In [79]:
a2 = np.arange(4) . reshape(1,4)
a2

array([[0, 1, 2, 3]])

In [81]:
a2[2:3]

array([[0, 1, 2, 3]])

In [82]:
a2[-1]

array([0, 1, 2, 3])

In [83]:
a4 = np.array([6,7,8])
a4[0:2]

array([6, 7])

In [84]:
a4[1:3]

array([7, 8])

In [85]:
a4[-1]

8

In [87]:
a5 = np.arange(9) .reshape(3,3)
a5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
a5[1:2]

[2]

In [99]:
a5[0:2]

[1, 2]

In [104]:
a6 = np.array([[6,7,8],[1,2,3],[9,3,2]])
a6

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [106]:
for row in a6:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [107]:
for cell in a6.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


# vstack and hstack

In [109]:
a =np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [110]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [111]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [113]:
result = np.vstack((a,b))

In [114]:
result

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [115]:
result[0]

array([0, 1])

In [116]:
result[3]

array([6, 7])

In [117]:
result1 = np.hstack((a,b))

In [118]:
result1

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [119]:
result1[1]

array([2, 3, 8, 9])

# bool

In [121]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [123]:
a[b] = -1

In [124]:
a[b]

array([-1, -1, -1, -1, -1, -1, -1])

# nditer

In [125]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
for x in np.nditer(a,order="c"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [127]:
for x in np.nditer(a,order="f"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [131]:
for x in np.nditer(a,order="f",flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [137]:
 a = np.arange(12).reshape(3,4)

In [139]:
b = np.arange(3).reshape(3,1)

In [140]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
2 0
3 0
4 1
5 1
6 1
7 1
8 2
9 2
10 2
11 2
