# Solving Questions of NumPy Matrix

**Get the maximum value from given matrix**

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.max()

5

**Get the minimum value from given matrix**

In [4]:
a1 = np.arange(6,22,3).reshape(3,2)

In [5]:
a1.min()

6

**Find the number of rows and columns of a given matrix using NumPy**

In [6]:
a2 = np.array([[1,5,3],[6,3,7],[9,6,4]])
a2

array([[1, 5, 3],
       [6, 3, 7],
       [9, 6, 4]])

In [7]:
a2.shape

(3, 3)

**Find the sum of values in a matrix**

In [8]:
a3 = np.arange(9).reshape(3,3)
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
a3.sum()

36

In [10]:
a3.sum(axis=1)

array([ 3, 12, 21])

In [11]:
a3.sum(axis=0)

array([ 9, 12, 15])

**Calculate the sum of the diagonal elements of a NumPy array**

In [12]:
a4 = np.arange(9).reshape(3,3)

In [13]:
a6 = np.arange(10,35,3).reshape(3,3)

In [14]:
add = np.diagonal(a4)

In [15]:
add.sum()

12

**multiplying Matrices in Python**

In [16]:
a5 = np.arange(1,10).reshape(3,3)

In [17]:
a6 = np.arange(10,35,3).reshape(3,3)

In [18]:
a9 = np.dot(a5,a6)
a9

array([[132, 150, 168],
       [303, 348, 393],
       [474, 546, 618]])

**Adding and Subtracting**

In [19]:
a5 = np.arange(1,10).reshape(3,3)
a5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a6 = np.arange(10,35,3).reshape(3,3)
a6

array([[10, 13, 16],
       [19, 22, 25],
       [28, 31, 34]])

In [21]:
a7 = np.add(a5,a6)
a7

array([[11, 15, 19],
       [23, 27, 31],
       [35, 39, 43]])

In [22]:
a8 = np.subtract(a6,a5)
a8

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

**Calculating Determinant of a 3X3 Numpy matrix**

In [23]:
b1 = np.arange(3,28,3).reshape(3,3)
b1

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [24]:
b2 = np.linalg.det(b1)
b2

0.0

In [25]:
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
n_array

array([[55, 25, 15],
       [30, 44,  2],
       [11, 45, 77]])

In [26]:
np.linalg.det(n_array)

137180.0000000001