# Question from geeksforgeeks

**How to create an empty and a full NumPy array?**

In [1]:
import numpy as np

In [3]:
a = np.empty((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
b = np.full([2,3],9)
b

array([[9, 9, 9],
       [9, 9, 9]])

**Create a Numpy array filled with all zeros**

In [5]:
a1 = np.zeros((3,3))
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Create a Numpy array filled with all ones**

In [6]:
a2 = np.ones((3,4))
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a2.ndim

2

In [8]:
a2.shape

(3, 4)

**Check whether a Numpy array contains a specified row**

In [11]:
a3 = np.arange(12).reshape(4,3)
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
([0,1,2])in a3.tolist()

True

In [15]:
([2,3,4,5]) in a3.tolist()

False

**How to Remove rows in Numpy array that contains non-numeric values?**

In [17]:
a4 = np.array([[1,2,3],[4,np.nan,np.nan],[np.nan,np.nan,9]])
a4

array([[ 1.,  2.,  3.],
       [ 4., nan, nan],
       [nan, nan,  9.]])

In [19]:
a4[~np.isnan(a4).any(axis=1)]

array([[1., 2., 3.]])

In [20]:
a4.ndim

2

In [21]:
a4.size

9

In [22]:
a4

array([[ 1.,  2.,  3.],
       [ 4., nan, nan],
       [nan, nan,  9.]])

In [23]:
a5 = np.array([[2,5,7],[3,7,np.nan],[8,0,3]])
a5

array([[ 2.,  5.,  7.],
       [ 3.,  7., nan],
       [ 8.,  0.,  3.]])

In [25]:
a5[~np.isnan(a5).any(axis=1)]

array([[2., 5., 7.],
       [8., 0., 3.]])

**Remove single-dimensional entries from the shape of an array**

In [26]:
a6 = np.arange(1,25,2).reshape(4,3)

In [28]:
a7 = np.squeeze(a6)
a7

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [30]:
a8 = np.arange(26,50,2).reshape(3,4)

In [31]:
a9 = np.squeeze(a8)
a9

array([[26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

**Find the number of occurrences of a sequence in a NumPy array**

In [32]:
a9 = np.array([[1,2,3],[2,3,2],[5,6,2]])

In [33]:
output = repr(a9).count("2")
output

4

**Combining a one and a two-dimensional NumPy Array**

In [39]:
b1 = np.arange(1,4).reshape(3,1)

In [41]:
b2 = np.arange(5,17).reshape(3,4)

In [42]:
for x,y in np.nditer([b1,b2]):
    print(x,y)

1 5
1 6
1 7
1 8
2 9
2 10
2 11
2 12
3 13
3 14
3 15
3 16


**How to compare two NumPy arrays?**

In [44]:
b3 = np.arange(1,7).reshape(2,3)

In [47]:
b4 = np.arange(8,14).reshape(2,3)

In [48]:
bool = b3 > b4
bool

array([[False, False, False],
       [False, False, False]])